name: Build PDF Documentation

on:
  push:
    branches: [main]

permissions: read-all

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@e2f99d4b3685b0da93f97e1b86ad8fab81105098 # v3
        with:
          root_file: main.tex
          working_directory: docs
          texlive_version: latest

      - name: Get date
        id: date
        run: echo "DATE=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Rename PDF
        run: mv docs/main.pdf docs/cdboost-experiments-${{ steps.date.outputs.DATE }}.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: cdboost-experiments-docs
          path: docs/cdboost-experiments-${{ steps.date.outputs.DATE }}.pdf
          retention-days: 14
